Repository iZettle/Form, pull requests merged in 2018-09, with the labels that each got.

#25 Fixed issue where Reusable configure as called instead of reconfigure…
  CHANGELOG.md
  Form/TableKit.swift
  Form/UICollectionViewCell+Utilities.swift
  Form/UITableViewCell+Utilities.swift
  FormTests/TableChangeTests.swift
Labels: bug

#28 Bumped version to version 1.2 (and skip never released 1.1.1 release)
  CHANGELOG.md
  Form/Info.plist
  FormFramework.podspec
Labels: enhancement

#29 Missed to flip Equatable comparison when changing isSame to its oppos…
  Form/MixedReusable.swift
Labels: bug

#34 Fixes compiler errors in Swift 4.2
  Examples/Demo/Example/Messages.swift
  Form/ValueField.swift
Labels: bug

#31 Use UITableViewAutomaticDimension instead of hardcoded height value
  Form/TableKit.swift
Labels: bug

#35 Bumped version to 1.3.0 and updated changelog
  CHANGELOG.md
  Form/Info.plist
  FormFramework.podspec
Labels: enhancement

#38 A keyboard notification UIKeyboardAnimationCurveUserInfoKey sometimes…
  Form/KeyboardEvent.swift
Labels: bug

#39 Updated ValueField to post UITextField notification to better partici…
  Form/ValueField.swift
Labels: bug, enhancement

#40 Bumped version to 1.3.1 and updated change log
  CHANGELOG.md
  Form/Info.plist
  FormFramework.podspec
Labels: enhancement

#43 Bugfix: Make sure `[animated keyPath:]` is animated with `.allowUserI…
  CHANGELOG.md
  Form/RowAndProvider.swift
  Form/UIView+Layout.swift
Labels: bug
