Repository iZettle/Form, pull requests merged in 2018-10, with the labels that each got.

#42 Fix update change index
  CHANGELOG.md
  Form/Collection+Changes.swift
  Form/CollectionAnimation.swift
  Form/TableChange.swift
  FormTests/CollectionDiffTests.swift
  FormTests/TableChangeTests.swift
Labels: bug

#45 Remove `carthage copy-frameworks` build step in Form.xcodeproj
  Form.xcodeproj/project.pbxproj
Labels: bug

#47 [release] Bump version to 1.3.2
  Form/Info.plist
  FormFramework.podspec
  FormTests/Info.plist
Labels: release

#57 TextFieldDelegate
  CHANGELOG.md
  Examples/Demo/Example/Contents.swift
  Form.xcodeproj/project.pbxproj
  Form/ScrollViewDelegate.swift
  Form/TextFieldDelegate.swift
Labels: enhancement

#59 Added remaining methods to `ScrollViewDelegete`.
  CHANGELOG.md
  Form/ScrollViewDelegate.swift
Labels: enhancement

#60 Fix table footer height on iOS 9
  Form/TableKit.swift
Labels: bug

#64 Fixed a bug in `UIScrollView.adjustContentOffset` for scrollviews wit…
  CHANGELOG.md
  Form/UIScrollView+Keyboard.swift
Labels: bug

#65 Fix cell background image missing on iOS 9 when inserting new cell
  Form/UITableViewCell+Utilities.swift
Labels: bug
