Repository iZettle/Form, pull requests merged in 2018-08, with the labels that each got.

#12 Fixes a bug in SelectView where tapping inside but releasing outside …
  Form/SelectView.swift
Labels: bug

#14 SectionView: Make sure to set height to 0 to avoid bug where the stac…
  Form/SectionView.swift
Labels: bug

#11 Fixes a bug with `install` view(s) into scroll views where the conten…
  Form/UIScrollView+Keyboard.swift
  Form/UIViewController+Install.swift
Labels: bug

#15 Bumped version to 1.0.2 and updated change log.
  CHANGELOG.md
  Form/Info.plist
  FormFramework.podspec
Labels: enhancement

#18 Force ValueField to never have autocorrection enabled as setting it t…
  Form/ValueField.swift
Labels: bug

#17 Updated NumberEditor to handle entering and editing of negative value…
  Form/NumberEditor.swift
  FormTests/NumberEditorTests.swift
Labels: bug, enhancement

#19 Pin tablekit empty view to edges
  Form/TableKit.swift
Labels: enhancement

#23 Setting a table's header and footer to a zero height does have the ex…
  Form/TableKit.swift
  Form/UITableView+Utilities.swift
Labels: bug

#21 TableKit cell dispose bag fix
  CHANGELOG.md
  Form/TableKit.swift
  Form/TableViewDelegate.swift
  Form/UITableViewCell+Utilities.swift
Labels: bug

#24 Improved support for tables with mixed types
  CHANGELOG.md
  Documentation/Tables.md
  Examples/Demo/Example.xcodeproj/project.pbxproj
  Examples/Demo/Example/Contents.swift
  Examples/Demo/Example/Tables.swift
  Form.xcodeproj/project.pbxproj
  Form/EitherRow.swift
  Form/MixedReusable.swift
  Form/Reusable.swift
  Form/UICollectionViewCell+Utilities.swift
  Form/UITableViewCell+Utilities.swift
Labels: enhancement
